[tool.poetry]
name = "ForecastDrift"
version = "0.1.4"
description = "Forecast Drift Detector for Views."
authors = ["Mihai Croicu <mihai.croicu@pcr.uu.se>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/prio-data/ForecastDrift>"

[tool.poetry.dependencies]
python = "^3.9"
pandas = ">1.2.3"
psycopg2-binary = "^2.9"
views_forecasts = "^0.5.4"
numpy = ">1.24"
ingester3 = ">1.9.0 <1.99.99"
viewser = ">5.10.0 <5.99.99"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
