[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]
[project]
name = "subtain-apimatic-sdk"
description = "This is a test package publishing, Please ignore"
version = "2.2.80"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["apimatic ", "Test"]
authors = [{name = "Subtain", email = "Syed.subtain@apimatic.io"}]
urls = {Documentation = "https://apimatic.io"}
dependencies = ["apimatic-core~=0.2.0", "apimatic-core-interfaces~=0.1.0", "apimatic-requests-client-adapter~=0.1.0", "python-dateutil~=2.8.1", "enum34~=1.1, >=1.1.10", "deprecation~=2.1", "jsonschema~=3.2.0"]
classifiers = []
[project.optional-dependencies]
testutils = ["pytest>=7.2.2"]
[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]
