[tool.poetry]
name = "dai-python-commons"
version = "5.3.15"
description = "Collection of small python utilities useful for lambda functions or glue jobs. By the Stockholm Public Transport Administration."
authors = []

[tool.poetry.dependencies]
python = "~3.10"
loguru = "^0.7.0"
boto3 = "^1.26.0"
awswrangler = { version = "3.2.1", optional = true }
boto3-stubs = { version = "^1.26.0", extras = ["s3", "glue"] }
cryptography = { version = "41.0.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "7.4"
moto = { version = "4.1.13", extras = ["s3", "glue"] }
pylint = "2.17.4"
black = "^23.7.0"

[tool.poetry.extras]
data-consolidation = ["polars"]
glue = ["awswrangler", "cryptography"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]
