[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "music_validator_micro"
version = "0.1.1"
authors = [
  { name="Samuel Shiels" },
]
description = "A media file tag checker tool, intended to work alone or fit into a larger toolchain"
readme = "README.md"
requires-python = ">=3.11.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
]