[tool.poetry]
name = "fractal-database"
version = "0.0.8"
description = ""
authors = ["Mo Balaa <balaa@fractalnetworks.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fractal-cli = ">=0.0.1"
fractal-database-matrix = ">=0.0.1"
django = ">=5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.plugins."fractal.plugins"]
"db" = "fractal_database.controllers.fractal_database_controller"
