[tool.poetry]
name = "ppi-origami"
version = "0.1.4"
description = "Tools for protein-protein interaction datasets."
authors = ["Joseph Szymborski <joseph.szymborski@mail.mcgill.ca>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{ include = "ppi_origami" }]
repository = "https://github.com/Emad-COMBINE-lab/ppi_origami"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
fire = "^0.5.0"
humanize = "^4.7.0"
rich = "^13.5.0"
plyvel = "^1.5.0"
tables = "^3.8.0"
requests = "^2.31.0"
defusedxml = "^0.7.1"
pandas = "^2.0.3"
sentencepiece = "^0.1.99"
scipy = "^1.11.1"
scikit-learn = "^1.3.0"
textdistance = {extras = ["extras"], version = "^4.5.0"}
pyexcel-ods3 = "^0.6.1"
pyprobables = "^0.5.8"


[tool.poetry.group.dev.dependencies]
black = { extras = ["d"], version = "^23.7.0" }
mkdocs = "^1.5.1"
mkdocs-material = "^9.1.21"
sphinx = "^7.2.6"
furo = "^2024.1.29"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ppi_origami = 'ppi_origami.__main__:main'
