[tool.poetry]
name = "evidi_fabric"
version = "0.1.13"
description = ""
authors = ["Uffe Friis Torlyn <uft@cloud-agility.com>"]
readme = "README.md"
packages = [{include = "evidi_fabric"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyspark = "^3.3.2"
delta = "^0.4.2"
delta-spark = "^2.2.0"
pyodbc = "^4.0.35"
pandas = "^1.5.3"
requests = "^2.28.2"
azure-keyvault-secrets = "^4.7.0"
azure-identity = "^1.12.0"
azure-core = "^1.26.3"
dynaconf = "^3.1.12"
azure-storage-file-datalake = "^12.10.1"
sqlalchemy = "^2.0.20"
twine = "^5.0.0"
semantic-link = "^0.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
