# the "wheel" crate is excluded from the workspace because pyo3 has problems with
# "cargo test" and "cargo bench"
[workspace]
members = [
    "chik-bls",
    "chik-bls/fuzz",
    "chik-client",
    "chik-protocol",
    "chik-protocol/fuzz",
    "chik_py_streamable_macro",
    "chik_streamable_macro",
    "chik-ssl",
    "chik-tools",
    "chik-traits",
    "chik-wallet",
    "klvm-derive",
    "klvm-traits",
    "klvm-utils",
    "klvm-utils/fuzz",
    "fuzz",
    "wasm",
]
exclude = ["wheel"]

[package]
name = "chik"
version = "0.2.15"
edition = "2021"
license = "Apache-2.0"
description = "Utility functions and types used by the Chik blockchain full node"
authors = ["Richard Kiss <him@richardkiss.com>", "Arvid Norberg <arvid@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chik_rs/"
repository = "https://github.com/Chik-Network/chik_rs/"

[features]
py-bindings = ["dep:pyo3"]

[dependencies]
klvmr = "=0.3.0"
hex = "=0.4.3"
pyo3 = { version = ">=0.19.0", optional = true }
klvm-utils = { version = "=0.2.12", path = "klvm-utils" }
chik-traits = { version = "=0.2.13", path = "chik-traits" }
klvm-traits = { version = "=0.2.12", path = "klvm-traits" }
klvm-derive = { version = "=0.2.12", path = "klvm-derive" }
chik-protocol = { version = "=0.2.13", path = "chik-protocol" }
chik-wallet = { version = "=0.2.12", path = "chik-wallet" }
hex-literal = "=0.4.1"
thiserror = "1.0.44"

[dev-dependencies]
num-traits = "=0.2.15"
rstest = "=0.16.0"
text-diff = "=0.4.0"

[lib]
name = "chik"
crate-type = ["rlib"]

[profile.release]
lto = "thin"

[patch.crates-io]
blst = { git = "https://github.com/supranational/blst.git", rev = "0d46eefa45fc1e57aceb42bba0e84eab3a7a9725" }
