load:
    login_code_description: "<h3>1. ğŸ”‘ Login code: Insert the login code you received:</h3>"
    login_code_label: "Login code"
    login_code_placeholder: "Insert login code..."
    login_code_info: "If you didn't receive a login code, please contact us."
    input_description: "<h3>2. ğŸ“ Input sentences: Upload a file containing source sentences and translations OR insert source sentences manually:</h3>"
    file_label: "Input file"
    sentences_label: "Input sentences"
    sentences_placeholder: "Insert one sentence with format SOURCE ||| TARGET per line..."
    start_button_label: "ğŸ“ Start"
translate:
    source_side_label: "<h3>Source sentences</h3>"
    target_side_label: "<h3>Translations with&nbsp;<span style='background-color: #fee2e2; color: black;'>potential issues</span></h3><p>Use the green checkmark to remove remaining highlights after editing.</p>"
    reload_button_label: "â¬…ï¸ Back to data loading"
    clear_button_label: "ğŸ—‘ï¸ Clear current changes"
    done_button_label: "âœ… Done"
    source_textbox_label: "Source text"
    target_textbox_label: "Translation"
    highlight_labels:
        - "Minor Error"
        - "Major Error"
    highlight_colors:
        - "#ccfbf1"
        - "#ffedd5"
