[tool.poetry]
name = "pytest-fixture-remover"
version = "1.0.1-post1"
description = "A LibCST codemod to remove pytest fixtures applied via the usefixtures decorator, as well as its parametrizations."
authors = ["Roman Vlasenko <klavionik@gmail.com>"]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Framework :: Pytest",
]
homepage = "https://github.com/Klavionik/pytest-fixture-remover"

[tool.poetry.dependencies]
python = "^3.8"
libcst = "^1.1.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.4.1"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
