api_endpoints:
    auth_token_url: https://auth-dev.syntheticabio.net/auth/realms/sbp-registry-svc-realm/protocol/openid-connect/token
    base_url: https://registry-api-dev.syntheticabio.net
    models: /v1/models
    models_by_operations: /v1/models/operation
    completions: /v1/completions
    upload_document: /v1/documents/upload
    documents: /v1/documents/
    search_default_collections: /v1/documents/search
    document_collections: /v1/document-collections
    search_document_collection: /v1/document-collections/search

