[project]
name = "LLMagic"
version = "0.0.3"
description = "LLMagic: A Python toolkit for building Large Language Model (LLM) apps with efficient wrappers. Simplify NLP development with battle-tested reliability for production environments. Unleash the power of LLMs effortlessly. Get started now!"
readme = "README.md"
requires-python = ">=3.8, <3.12"
license = {file = "LICENSE"}
keywords = ["LLMagic", "Large Language Model Application", "Development"]
authors = [
    {name = "Soumadip Saha", email = "soumadipsaha2000@gmail.com"}
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only"
]

dependencies = [

]

[project.optional-dependencies]
llama-gpu = ["llama-cpp-python"]

[project.urls]
"Homepage" = "https://github.com/Soumadip-Saha/LLMagic"
"Source" = "https://github.com/Soumadip-Saha/LLMagic"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
