[tool.poetry]
name = "ytvs"
version = "0.0.19"
description = ""
authors = ["HHH_HHH <kukkuk989@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
