[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nasa_pace_data_reader"
version = "0.0.3.8"
authors = [
  { name="Anin Puthukkudy", email="aputhukkudy@umbc.edu" },
]
description = "A package for reading NASA PACE data files."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib>=3.6",
    "basemap>=1.3.0",
    "numpy>=1.21.2",
    "netCDF4>=1.5.7",
    "basemap-data-hires>=1.2.1",
    "Bottleneck>=1.3.2",
    "scipy>=1.7.1",
    "notebook>=6.4.3",
    "statsmodels>=0.12.2",
]

[project.urls]
Homepage = "https://github.com/aninramesh/nasa-pace-data-reader"
Issues = "https://github.com/aninramesh/nasa-pace-data-reader/issues"