[tool.poetry]
name = "redshift-data-api"
version = "1.2.2"
description = ""
authors = ["Giacomo Tagliabue <giacomo.tag@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

# versions need to be exact as they're currently installed in airflow via requirements.txt
boto3 = "1.26.161"
pandas = "1.5.3"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
flake8 = "^7.0.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target_version = ['py310']
