[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "webapicontrollers"
version = "0.0.16"
authors = [
  { name="Coding Flow" },
]
description = "A basic API controller framework built on top of FastAPI"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


dependencies = [
  "annotated-types ~= 0.6.0",
  "anyio ~= 4.2.0",
  "click ~= 8.1.7",
  "colorama ~= 0.4.6",
  "fastapi ~= 0.109.0",
  "h11 ~= 0.14.0",
  "idna ~= 3.6",
  "pydantic ~= 2.5.3",
  "pydantic_core ~= 2.14.6",
  "sniffio ~= 1.3.0",
  "starlette ~= 0.35.1",
  "typing_extensions ~= 4.9.0",
  "uvicorn ~= 0.27.0"
]

[project.urls]
Homepage = "https://github.com/codingflowdev/web-api-controllers"

[tool.hatch.build.targets.wheel]
exclude = ["src/app.py"]

[tool.hatch.build.targets.sdist]
exclude = ["src/app.py"]

