[tool.poetry]
name = "kudaf_jupyter_server_extension"
version = "0.1.5"
description = "Kudaf Data Consumer Jupyter server extension for JupyterLab. It provides the basic infrastructure to interact with the Kudaf system"
authors = ["Daniel Díguele,  Sikt - Kunnskapssektorens tjenesteleverandør  <daniel.diguele@sikt.no>"]
maintainers = ["Daniel Díguele,  Sikt - Kunnskapssektorens tjenesteleverandør  <daniel.diguele@sikt.no>"]
repository = "https://gitlab.sikt.no/kudaf/jupyterlab"
license = "MIT License"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Jupyter :: JupyterLab",
]
packages = [{include = "kudaf_extension"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
aiodns = "^3.1.1"
aiohttp = "^3.9.3"
aiohttp-debugtoolbar = "^0.6.1"
aiohttp-jinja2 = "^1.6"
aiosignal = "^1.3.1"
anyio = "^4.2.0"
argon2-cffi = "^23.1.0"
argon2-cffi-bindings = "^21.2.0"
arrow = "^1.3.0"
asttokens = "^2.4.1"
async-lru = "^2.0.4"
async-timeout = "^4.0.3"
attrs = "^23.2.0"
authlib = "^1.3.0"
babel = "^2.14.0"
backcall = "^0.2.0"
beautifulsoup4 = "^4.12.3"
bleach = "^6.1.0"
certifi = "^2023.11.17"
cffi = "^1.16.0"
charset-normalizer = "^3.3.2"
comm = "^0.2.1"
contourpy = "^1.2.0"
cycler = "^0.12.1"
debugpy = "^1.8.0"
decorator = "^5.1.1"
defusedxml = "^0.7.1"
easyprocess = "^1.1"
entrypoint2 = "^1.1"
et-xmlfile = "^1.1.0"
exceptiongroup = "^1.2.0"
executing = "^2.0.1"
fastjsonschema = "^2.19.1"
fonttools = "^4.47.2"
fqdn = "^1.5.1"
frozenlist = "^1.4.1"
h11 = "^0.14.0"
httpcore = "^1.0.2"
httpx = "^0.26.0"
idna = "^3.6"
ipykernel = "^6.29.0"
ipylab = "^1.0.0"
ipython-genutils = "^0.2.0"
ipywidgets = "^8.1.1"
isoduration = "^20.11.0"
jedi = "^0.19.1"
jeepney = "^0.8.0"
jinja2 = "^3.1.3"
json-stream = "^2.3.2"
json-stream-rs-tokenizer = "^0.4.25"
json5 = "^0.9.14"
jsonpointer = "^2.4"
jsonschema = "^4.21.1"
jupyter-app-launcher = "^0.2.1"
jupyter-contrib-core = "^0.4.2"
jupyter-contrib-nbextensions = "^0.7.0"
jupyter-events = "^0.9.0"
jupyter-highlight-selected-word = "^0.2.0"
jupyter-lsp = "^2.2.2"
jupyter-nbextensions-configurator = "^0.6.3"
jupyter-client = "^8.6.0"
jupyter-core = "^5.7.1"
jupyter-server = "^2.12.5"
jupyter-server-proxy = "^4.1.0"
jupyter-server-terminals = "^0.5.2"
jupyterlab = "^4.0.11"
jupyterlab-pygments = "^0.3.0"
jupyterlab-widgets = "^3.0.9"
jupyterlab-server = "^2.25.2"
jupyterlab-templates = "^0.5.0"
kiwisolver = "^1.4.5"
lxml = "^5.1.0"
markupsafe = "^2.1.4"
matplotlib = "^3.8.2"
matplotlib-inline = "^0.1.6"
mistune = "^3.0.2"
mouseinfo = "^0.1.3"
mss = "^9.0.1"
multidict = "^6.0.4"
nbclassic = "^1.0.0"
nbclient = "^0.9.0"
nbconvert = "^7.14.2"
nbformat = "^5.9.2"
nest-asyncio = "^1.6.0"
notebook = "^7.0.7"
notebook-shim = "^0.2.3"
numpy = "^1.26.3"
openpyxl = "^3.1.2"
overrides = "^7.7.0"
packaging = "^23.2"
pandas = "^2.2.0"
pandocfilters = "^1.5.1"
parso = "^0.8.3"
pexpect = "^4.9.0"
pickleshare = "^0.7.5"
pillow = "^10.2.0"
platformdirs = "^4.1.0"
prometheus-client = "^0.19.0"
prompt-toolkit = "^3.0.43"
psutil = "^5.9.8"
ptyprocess = "^0.7.0"
pure-eval = "^0.2.2"
pyautogui = "^0.9.54"
pycares = "^4.4.0"
pycparser = "^2.21"
pygetwindow = "^0.0.9"
pygments = "^2.17.2"
pyjwt = "^2.8.0"
pymsgbox = "^1.0.9"
pyparsing = "^3.1.1"
pyperclip = "^1.8.2"
pyrect = "^0.2.0"
pyrsistent = "^0.20.0"
pyscreenshot = "^3.1"
pyscreeze = "^0.1.30"
python-dateutil = "^2.8.2"
python-dotenv = "^1.0.1"
python-json-logger = "^2.0.7"
python3-xlib = "^0.15"
pytweening = "^1.0.7"
pytz = "^2023.4"
pyyaml = "^6.0.1"
pyzmq = "^25.1.2"
requests = "^2.31.0"
rfc3339-validator = "^0.1.4"
rfc3986-validator = "^0.1.1"
send2trash = "^1.8.2"
simpervisor = "^1.0.0"
six = "^1.16.0"
sniffio = "^1.3.0"
soupsieve = "^2.5"
stack-data = "^0.6.3"
tenacity = "^8.2.3"
terminado = "^0.18.0"
tinycss2 = "^1.2.1"
tomli = "^2.0.1"
tornado = "^6.4"
traitlets = "^5.14.1"
typing-extensions = "^4.9.0"
tzdata = "^2023.4"
uri-template = "^1.3.0"
urllib3 = "^2.1.0"
wcwidth = "^0.2.13"
webcolors = "^1.13"
webencodings = "^0.5.1"
websocket-client = "^1.7.0"
widgetsnbextension = "^4.0.9"
yarl = "^1.9.4"
ipython = "^8.20.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.272"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
cryptography = "^41.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=79

[project.urls]
"Homepage" = "https://gitlab.sikt.no/kudaf/jupyterlab"
"Bug Tracker" = "https://gitlab.sikt.no/kudaf/jupyterlab/issues"