[project]
name = "ez_validate"
version = "0.0.4"
authors = [
  { name="OLODiman11", email="olodiman11@mail.ru" },
]
description = "Builder-like data validation package"
readme = "README.md"
requires-python = ">=2.7"
classifiers = [
    "Programming Language :: Python :: 2",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]