[package]
name = "OxVoxNNS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ox_vox_nns"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.0"
numpy = "0.18"
rayon = "1.8.1"
